apiVersion: v1
kind: ReplicationController
metadata:
  name: ajsc6configdemo
  namespace: org-onap-aai
spec:
  replicas: 5
  selector:
    app: ajsc6configdemo
  template:
    metadata:
      labels:
        app: ajsc6configdemo
    spec:
      serviceAccount: ajsc-svc-account
      containers:
      - name: ajsc6configdemo
        volumeMounts:
        - name: myservice-properties-volume
          mountPath: /etc/config/dynamic
        image: zlp11313.vci.att.com:5100/com.att.ajsc/ajsc6configdemo:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
      volumes:
      - name: myservice-properties-volume
        configMap:
          name: ajsc6configdemo-dynamic-properties